language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip
before_install: cp "${TRAVIS_BUILD_DIR}/server/config_values.go.template" "${TRAVIS_BUILD_DIR}/server/config_values.go"
install: go get -tags 'standalone' -t ./...
before_script:
script: go test -tags 'standalone' -v ./...
